import ast
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_INIT = PROJECT_ROOT / "src" / "news_decomp" / "__init__.py"
API_DOC = PROJECT_ROOT / "docs" / "api.md"


def read_exports(path: Path) -> list[str]:
    """Read a module's literal ``__all__`` declaration without importing it."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in targets
        ):
            exports = ast.literal_eval(node.value)
            if not isinstance(exports, list) or not all(
                isinstance(name, str) for name in exports
            ):
                raise ValueError(f"{path}: __all__ must be a literal list of strings")
            return exports
    raise ValueError(f"{path}: no literal __all__ declaration found")


def render_api_page(exports: list[str]) -> str:
    """Render the Markdown manifest that mkdocstrings consumes."""
    lines = [
        "# API Reference",
        "",
        (
            "This file is generated by `scripts/generate_api_docs.py` from the "
            "package's `__all__` declaration. The API content is rendered from "
            "the current source during each Zensical build."
        ),
        "",
        "## Public API",
        "",
    ]
    for name in exports:
        lines.extend(
            (
                f"::: news_decomp.{name}",
                "    options:",
                "      show_source: false",
                "      show_root_heading: true",
                "",
            )
        )
    return "\n".join(lines)


def main() -> None:
    """Update the generated API documentation manifest from package exports."""
    API_DOC.write_text(render_api_page(read_exports(PACKAGE_INIT)), encoding="utf-8")


if __name__ == "__main__":
    main()
